import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="">
      <body
        className={
          `${geistSans.variable} ${geistMono.variable} antialiased overflow-x-hidden dark:bg-[#222]`
        }
      >
        <div className="sm:mx-5 lg:mx-auto max-w-screen-2xl">
          {children}
          <Toaster />
        </div>
      </body>
    </html>
  );
}
